package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"
	"metachat/internal/graphql/graph/model"
	"metachat/internal/models"
	"metachat/internal/services"
	"metachat/pkg/utils"
	"strconv"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (string, error) {
	user, err := r.UserRepo.GetByName(input.Name)
	if err != nil {
		return "", fmt.Errorf("invalid credentials")
	}

	if !user.VerifyPassword(input.Password) {
		return "", fmt.Errorf("invalid credentials")
	}

	token, err := utils.GenerateToken(user.ID, user.Name)
	if err != nil {
		return "", fmt.Errorf("failed to generate token: %w", err)
	}

	return token, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user := &models.User{
		Name: input.Name,
	}
	if err := user.HashPassword(input.Password); err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	if err := r.UserRepo.Create(user); err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	diaryChat := &models.Chat{
		Name:  "Дневник",
		Users: []models.User{*user},
	}
	if err := r.ChatRepo.Create(diaryChat); err != nil {
		return nil, fmt.Errorf("failed to create diary chat: %w", err)
	}

	diary := &models.Diary{
		UserID: user.ID,
		ChatID: diaryChat.ID,
		Data:   models.JSONB{},
	}
	if err := r.DiaryRepo.Create(diary); err != nil {
		return nil, fmt.Errorf("failed to create diary: %w", err)
	}

	return toGraphQLUser(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	id, err := strconv.ParseUint(input.ID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.GetByID(uint(id))
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	if input.Name != nil {
		user.Name = *input.Name
	}
	if input.Password != nil {
		if err := user.HashPassword(*input.Password); err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
	}

	if err := r.UserRepo.Update(user); err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.UserRepo.Delete(uint(userID)); err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	return true, nil
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, input model.CreateChatInput) (*model.Chat, error) {
	chat := &models.Chat{
		Name: input.Name,
	}

	var users []models.User
	for _, userIDStr := range input.UserIds {
		userID, err := strconv.ParseUint(userIDStr, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("invalid user ID: %w", err)
		}

		user, err := r.UserRepo.GetByID(uint(userID))
		if err != nil {
			return nil, fmt.Errorf("user not found: %w", err)
		}
		users = append(users, *user)
	}
	chat.Users = users

	if err := r.ChatRepo.Create(chat); err != nil {
		return nil, fmt.Errorf("failed to create chat: %w", err)
	}

	createdChat, err := r.ChatRepo.GetByID(chat.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch created chat: %w", err)
	}

	return toGraphQLChat(createdChat), nil
}

// UpdateChat is the resolver for the updateChat field.
func (r *mutationResolver) UpdateChat(ctx context.Context, input model.UpdateChatInput) (*model.Chat, error) {
	chatID, err := uuid.Parse(input.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	chat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("chat not found: %w", err)
	}

	if input.Name != nil {
		chat.Name = *input.Name
	}

	if input.UserIds != nil {
		for _, userIDStr := range input.UserIds {
			userID, err := strconv.ParseUint(userIDStr, 10, 32)
			if err != nil {
				return nil, fmt.Errorf("invalid user ID: %w", err)
			}
			if err := r.ChatRepo.AddUserToChat(chatID, uint(userID)); err != nil {
				return nil, fmt.Errorf("failed to add user to chat: %w", err)
			}
		}
	}

	if err := r.ChatRepo.Update(chat); err != nil {
		return nil, fmt.Errorf("failed to update chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string) (bool, error) {
	chatID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid chat ID: %w", err)
	}

	if err := r.ChatRepo.Delete(chatID); err != nil {
		return false, fmt.Errorf("failed to delete chat: %w", err)
	}

	return true, nil
}

// AddUserToChat is the resolver for the addUserToChat field.
func (r *mutationResolver) AddUserToChat(ctx context.Context, chatID string, userID string) (*model.Chat, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.ChatRepo.AddUserToChat(chatUUID, uint(userIDUint)); err != nil {
		return nil, fmt.Errorf("failed to add user to chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// RemoveUserFromChat is the resolver for the removeUserFromChat field.
func (r *mutationResolver) RemoveUserFromChat(ctx context.Context, chatID string, userID string) (*model.Chat, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.ChatRepo.RemoveUserFromChat(chatUUID, uint(userIDUint)); err != nil {
		return nil, fmt.Errorf("failed to remove user from chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// CreateChatHistory is the resolver for the createChatHistory field.
func (r *mutationResolver) CreateChatHistory(ctx context.Context, input model.CreateChatHistoryInput) (*model.ChatHistory, error) {
	userIDStr := input.UserID
	if userIDStr == "" {
		if userIDVal := ctx.Value("userID"); userIDVal != nil {
			if userID, ok := userIDVal.(uint); ok {
				userIDStr = fmt.Sprintf("%d", userID)
			}
		}
	}

	userIDUint, err := strconv.ParseUint(userIDStr, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	userID := uint(userIDUint)

	chatID, err := uuid.Parse(input.ChatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	history := &models.ChatHistory{
		ChatID:      chatID,
		UserID:      userID,
		MessageText: input.MessageText,
		Type:        "normal",
	}

	if input.Type != nil {
		history.Type = *input.Type
	}

	healthDataList, err := r.HealthDataRepo.GetByUserID(userID, 1, 0)
	if err == nil && len(healthDataList) > 0 {
		latestHealth := healthDataList[0]
		if latestHealth.HeartRate != nil {
			aiResp, err := r.AIService.PredictEmotion(services.AIRequest{
				HeartRate: *latestHealth.HeartRate,
			})
			if err == nil && aiResp != nil {
				emotionID := aiResp.PredictedEmotionID
				emotionLabel := aiResp.PredictedEmotion
				confidence := aiResp.Confidence
				history.Emotion = &emotionID
				history.EmotionLabel = &emotionLabel
				history.EmotionConfidence = &confidence
			}
		}
	}

	if err := r.ChatHistoryRepo.Create(history); err != nil {
		return nil, fmt.Errorf("failed to create chat history: %w", err)
	}

	var emotion *int32
	if history.Emotion != nil {
		val := int32(*history.Emotion)
		emotion = &val
	}

	return &model.ChatHistory{
		ID:                history.ID.String(),
		ChatID:            history.ChatID.String(),
		UserID:            fmt.Sprintf("%d", history.UserID),
		MessageText:       history.MessageText,
		Type:              history.Type,
		Emotion:           emotion,
		EmotionLabel:      history.EmotionLabel,
		EmotionConfidence: history.EmotionConfidence,
		CreatedAt:         time.Unix(history.CreatedAt, 0),
	}, nil
}

// DeleteChatHistory is the resolver for the deleteChatHistory field.
func (r *mutationResolver) DeleteChatHistory(ctx context.Context, id string) (bool, error) {
	historyID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid history ID: %w", err)
	}

	if err := r.ChatHistoryRepo.Delete(historyID); err != nil {
		return false, fmt.Errorf("failed to delete chat history: %w", err)
	}

	return true, nil
}

// UpdateDiary is the resolver for the updateDiary field.
func (r *mutationResolver) UpdateDiary(ctx context.Context, userID string, data map[string]any) (*model.Diary, error) {
	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	userIDInt := uint(userIDUint)

	diary, err := r.DiaryRepo.GetByUserID(userIDInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get diary: %w", err)
	}

	diaryData := models.JSONB{}
	for k, v := range data {
		diaryData[k] = v
	}
	diary.Data = diaryData

	if err := r.DiaryRepo.Update(diary); err != nil {
		return nil, fmt.Errorf("failed to update diary: %w", err)
	}

	resultData := make(map[string]any)
	if diary.Data != nil {
		for k, v := range diary.Data {
			resultData[k] = v
		}
	}

	return &model.Diary{
		ID:        fmt.Sprintf("%d", diary.ID),
		UserID:    fmt.Sprintf("%d", diary.UserID),
		ChatID:    diary.ChatID.String(),
		Data:      resultData,
		CreatedAt: diary.CreatedAt,
		UpdatedAt: diary.UpdatedAt,
	}, nil
}

// CreateHealthData is the resolver for the createHealthData field.
func (r *mutationResolver) CreateHealthData(ctx context.Context, input model.CreateHealthDataInput) (*model.HealthData, error) {
	userIDVal := ctx.Value("userID")
	if userIDVal == nil {
		return nil, fmt.Errorf("unauthorized: user ID not found in context")
	}

	userID, ok := userIDVal.(uint)
	if !ok {
		return nil, fmt.Errorf("invalid user ID type in context")
	}

	healthData := &models.HealthData{
		UserID:    userID,
		HeartRate: input.HeartRate,
		SDNN:      input.Sdnn,
		RMSSD:     input.Rmssd,
		PNN50:     input.Pnn50,
		Timestamp: input.Timestamp.Unix(),
	}

	if healthData.HeartRate != nil {
		aiResp, err := r.AIService.PredictEmotion(services.AIRequest{
			HeartRate: *healthData.HeartRate,
		})
		if err != nil {
			fmt.Printf("Error predicting emotion for heart rate %.2f: %v\n", *healthData.HeartRate, err)
		} else if aiResp != nil {
			emotionID := aiResp.PredictedEmotionID
			emotionLabel := aiResp.PredictedEmotion
			confidence := aiResp.Confidence
			healthData.Emotion = &emotionID
			healthData.EmotionLabel = &emotionLabel
			healthData.EmotionConfidence = &confidence
			fmt.Printf("Emotion predicted: %s (ID: %d, confidence: %.2f) for heart rate: %.2f\n", emotionLabel, emotionID, confidence, *healthData.HeartRate)
		} else {
			fmt.Printf("AI service returned nil response for heart rate %.2f\n", *healthData.HeartRate)
		}
	} else {
		fmt.Printf("HeartRate is nil, skipping emotion prediction\n")
	}

	if err := r.HealthDataRepo.Create(healthData); err != nil {
		return nil, fmt.Errorf("failed to create health data: %w", err)
	}

	var emotion *int32
	if healthData.Emotion != nil {
		val := int32(*healthData.Emotion)
		emotion = &val
	}

	return &model.HealthData{
		ID:                healthData.ID.String(),
		UserID:            fmt.Sprintf("%d", healthData.UserID),
		HeartRate:         healthData.HeartRate,
		Sdnn:              healthData.SDNN,
		Rmssd:             healthData.RMSSD,
		Pnn50:             healthData.PNN50,
		Emotion:           emotion,
		EmotionLabel:      healthData.EmotionLabel,
		EmotionConfidence: healthData.EmotionConfidence,
		Timestamp:         time.Unix(healthData.Timestamp, 0),
		CreatedAt:         time.Unix(healthData.CreatedAt, 0),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.GetByID(uint(userID))
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return toGraphQLUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	limitInt := 100
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	users, err := r.UserRepo.List(limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}

	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = &model.User{
			ID:        fmt.Sprintf("%d", u.ID),
			Name:      u.Name,
			CreatedAt: u.CreatedAt,
			UpdatedAt: u.UpdatedAt,
		}
	}

	return result, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id string) (*model.Chat, error) {
	chatID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	chat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("chat not found: %w", err)
	}

	return toGraphQLChat(chat), nil
}

// Chats is the resolver for the chats field.
func (r *queryResolver) Chats(ctx context.Context, limit *int32, offset *int32) ([]*model.Chat, error) {
	limitInt := 100
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	chats, err := r.ChatRepo.List(limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get chats: %w", err)
	}

	result := make([]*model.Chat, len(chats))
	for i, c := range chats {
		result[i] = toGraphQLChat(&c)
	}

	return result, nil
}

// ChatHistory is the resolver for the chatHistory field.
func (r *queryResolver) ChatHistory(ctx context.Context, id string) (*model.ChatHistory, error) {
	historyID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid history ID: %w", err)
	}

	history, err := r.ChatHistoryRepo.GetByID(historyID)
	if err != nil {
		return nil, fmt.Errorf("failed to get chat history: %w", err)
	}

	var emotion *int32
	if history.Emotion != nil {
		val := int32(*history.Emotion)
		emotion = &val
	}

	return &model.ChatHistory{
		ID:                history.ID.String(),
		ChatID:            history.ChatID.String(),
		UserID:            fmt.Sprintf("%d", history.UserID),
		MessageText:       history.MessageText,
		Type:              history.Type,
		Emotion:           emotion,
		EmotionLabel:      history.EmotionLabel,
		EmotionConfidence: history.EmotionConfidence,
		CreatedAt:         time.Unix(history.CreatedAt, 0),
	}, nil
}

// ChatHistories is the resolver for the chatHistories field.
func (r *queryResolver) ChatHistories(ctx context.Context, chatID string, limit *int32) ([]*model.ChatHistory, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	limitInt := 100
	if limit != nil {
		limitInt = int(*limit)
	}

	histories, err := r.ChatHistoryRepo.GetByChatID(chatUUID, limitInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get chat histories: %w", err)
	}

	result := make([]*model.ChatHistory, len(histories))
	for i, h := range histories {
		var emotion *int32
		if h.Emotion != nil {
			val := int32(*h.Emotion)
			emotion = &val
		}

		result[i] = &model.ChatHistory{
			ID:                h.ID.String(),
			ChatID:            h.ChatID.String(),
			UserID:            fmt.Sprintf("%d", h.UserID),
			MessageText:       h.MessageText,
			Type:              h.Type,
			Emotion:           emotion,
			EmotionLabel:      h.EmotionLabel,
			EmotionConfidence: h.EmotionConfidence,
			CreatedAt:         time.Unix(h.CreatedAt, 0),
		}
	}

	return result, nil
}

// Diary is the resolver for the diary field.
func (r *queryResolver) Diary(ctx context.Context, userID string) (*model.Diary, error) {
	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	userIDInt := uint(userIDUint)

	diary, err := r.DiaryRepo.GetByUserID(userIDInt)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get diary: %w", err)
	}

	data := make(map[string]any)
	if diary.Data != nil {
		for k, v := range diary.Data {
			data[k] = v
		}
	}

	return &model.Diary{
		ID:        fmt.Sprintf("%d", diary.ID),
		UserID:    fmt.Sprintf("%d", diary.UserID),
		ChatID:    diary.ChatID.String(),
		Data:      data,
		CreatedAt: diary.CreatedAt,
		UpdatedAt: diary.UpdatedAt,
	}, nil
}

// HealthData is the resolver for the healthData field.
func (r *queryResolver) HealthData(ctx context.Context, userID string, startDate *time.Time, endDate *time.Time, limit *int32, offset *int32) ([]*model.HealthData, error) {
	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	userIDInt := uint(userIDUint)

	limitInt := 100
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	var healthDataList []models.HealthData
	if startDate != nil || endDate != nil {
		healthDataList, err = r.HealthDataRepo.GetByUserIDAndDateRange(userIDInt, startDate, endDate, limitInt, offsetInt)
	} else {
		healthDataList, err = r.HealthDataRepo.GetByUserID(userIDInt, limitInt, offsetInt)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to get health data: %w", err)
	}

	result := make([]*model.HealthData, len(healthDataList))
	for i, h := range healthDataList {
		var emotion *int32
		if h.Emotion != nil {
			val := int32(*h.Emotion)
			emotion = &val
		}

		result[i] = &model.HealthData{
			ID:                h.ID.String(),
			UserID:            fmt.Sprintf("%d", h.UserID),
			HeartRate:         h.HeartRate,
			Sdnn:              h.SDNN,
			Rmssd:             h.RMSSD,
			Pnn50:             h.PNN50,
			Emotion:           emotion,
			EmotionLabel:      h.EmotionLabel,
			EmotionConfidence: h.EmotionConfidence,
			Timestamp:         time.Unix(h.Timestamp, 0),
			CreatedAt:         time.Unix(h.CreatedAt, 0),
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.

func toGraphQLUser(u *models.User) *model.User {
	return &model.User{
		ID:        fmt.Sprintf("%d", u.ID),
		Name:      u.Name,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
}
func toGraphQLChat(c *models.Chat) *model.Chat {
	users := make([]*model.User, len(c.Users))
	for i, u := range c.Users {
		users[i] = toGraphQLUser(&u)
	}
	return &model.Chat{
		ID:        c.ID.String(),
		Name:      c.Name,
		Users:     users,
		CreatedAt: c.CreatedAt,
		UpdatedAt: c.UpdatedAt,
	}
}
