package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"metachat/internal/graphql/graph/model"
	"metachat/internal/models"
	"metachat/pkg/utils"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (string, error) {
	user, err := r.UserRepo.GetByName(input.Name)
	if err != nil {
		return "", fmt.Errorf("invalid credentials")
	}

	if !user.VerifyPassword(input.Password) {
		return "", fmt.Errorf("invalid credentials")
	}

	token, err := utils.GenerateToken(user.ID, user.Name)
	if err != nil {
		return "", fmt.Errorf("failed to generate token: %w", err)
	}

	return token, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user := &models.User{
		Name: input.Name,
	}
	if err := user.HashPassword(input.Password); err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	if err := r.UserRepo.Create(user); err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	diaryChat := &models.Chat{
		Name:  "Дневник",
		Users: []models.User{*user},
	}
	if err := r.ChatRepo.Create(diaryChat); err != nil {
		return nil, fmt.Errorf("failed to create diary chat: %w", err)
	}

	diary := &models.Diary{
		UserID: user.ID,
		ChatID: diaryChat.ID,
		Data:   models.JSONB{},
	}
	if err := r.DiaryRepo.Create(diary); err != nil {
		return nil, fmt.Errorf("failed to create diary: %w", err)
	}

	return toGraphQLUser(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	id, err := strconv.ParseUint(input.ID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.GetByID(uint(id))
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	if input.Name != nil {
		user.Name = *input.Name
	}
	if input.Password != nil {
		if err := user.HashPassword(*input.Password); err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
	}

	if err := r.UserRepo.Update(user); err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.UserRepo.Delete(uint(userID)); err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	return true, nil
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, input model.CreateChatInput) (*model.Chat, error) {
	chat := &models.Chat{
		Name: input.Name,
	}

	var users []models.User
	for _, userIDStr := range input.UserIds {
		userID, err := strconv.ParseUint(userIDStr, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("invalid user ID: %w", err)
		}

		user, err := r.UserRepo.GetByID(uint(userID))
		if err != nil {
			return nil, fmt.Errorf("user not found: %w", err)
		}
		users = append(users, *user)
	}
	chat.Users = users

	if err := r.ChatRepo.Create(chat); err != nil {
		return nil, fmt.Errorf("failed to create chat: %w", err)
	}

	createdChat, err := r.ChatRepo.GetByID(chat.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch created chat: %w", err)
	}

	return toGraphQLChat(createdChat), nil
}

// UpdateChat is the resolver for the updateChat field.
func (r *mutationResolver) UpdateChat(ctx context.Context, input model.UpdateChatInput) (*model.Chat, error) {
	chatID, err := uuid.Parse(input.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	chat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("chat not found: %w", err)
	}

	if input.Name != nil {
		chat.Name = *input.Name
	}

	if input.UserIds != nil {
		for _, userIDStr := range input.UserIds {
			userID, err := strconv.ParseUint(userIDStr, 10, 32)
			if err != nil {
				return nil, fmt.Errorf("invalid user ID: %w", err)
			}
			if err := r.ChatRepo.AddUserToChat(chatID, uint(userID)); err != nil {
				return nil, fmt.Errorf("failed to add user to chat: %w", err)
			}
		}
	}

	if err := r.ChatRepo.Update(chat); err != nil {
		return nil, fmt.Errorf("failed to update chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string) (bool, error) {
	chatID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid chat ID: %w", err)
	}

	if err := r.ChatRepo.Delete(chatID); err != nil {
		return false, fmt.Errorf("failed to delete chat: %w", err)
	}

	return true, nil
}

// AddUserToChat is the resolver for the addUserToChat field.
func (r *mutationResolver) AddUserToChat(ctx context.Context, chatID string, userID string) (*model.Chat, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.ChatRepo.AddUserToChat(chatUUID, uint(userIDUint)); err != nil {
		return nil, fmt.Errorf("failed to add user to chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// RemoveUserFromChat is the resolver for the removeUserFromChat field.
func (r *mutationResolver) RemoveUserFromChat(ctx context.Context, chatID string, userID string) (*model.Chat, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	if err := r.ChatRepo.RemoveUserFromChat(chatUUID, uint(userIDUint)); err != nil {
		return nil, fmt.Errorf("failed to remove user from chat: %w", err)
	}

	updatedChat, err := r.ChatRepo.GetByID(chatUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated chat: %w", err)
	}

	return toGraphQLChat(updatedChat), nil
}

// CreateChatHistory is the resolver for the createChatHistory field.
func (r *mutationResolver) CreateChatHistory(ctx context.Context, input model.CreateChatHistoryInput) (*model.ChatHistory, error) {
	chatID, err := uuid.Parse(input.ChatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	userID, err := strconv.ParseUint(input.UserID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	historyType := "normal"
	if input.Type != nil {
		historyType = *input.Type
	}

	history := &models.ChatHistory{
		ChatID:      chatID,
		UserID:      uint(userID),
		MessageText: input.MessageText,
		Type:        historyType,
	}

	if err := r.ChatHistoryRepo.Create(history); err != nil {
		return nil, fmt.Errorf("failed to create chat history: %w", err)
	}

	createdHistory, err := r.ChatHistoryRepo.GetByID(history.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch created chat history: %w", err)
	}

	return toGraphQLChatHistory(createdHistory), nil
}

// DeleteChatHistory is the resolver for the deleteChatHistory field.
func (r *mutationResolver) DeleteChatHistory(ctx context.Context, id string) (bool, error) {
	historyID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid chat history ID: %w", err)
	}

	if err := r.ChatHistoryRepo.Delete(historyID); err != nil {
		return false, fmt.Errorf("failed to delete chat history: %w", err)
	}

	return true, nil
}

// UpdateDiary is the resolver for the updateDiary field.
func (r *mutationResolver) UpdateDiary(ctx context.Context, userID string, data map[string]any) (*model.Diary, error) {
	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	diary, err := r.DiaryRepo.GetByUserID(uint(userIDUint))
	if err != nil {
		return nil, fmt.Errorf("diary not found: %w", err)
	}

	diary.Data = models.JSONB(data)
	if err := r.DiaryRepo.Update(diary); err != nil {
		return nil, fmt.Errorf("failed to update diary: %w", err)
	}

	updatedDiary, err := r.DiaryRepo.GetByID(diary.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated diary: %w", err)
	}

	return toGraphQLDiary(updatedDiary), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.UserRepo.GetByID(uint(userID))
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return toGraphQLUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	limitVal := 100
	if limit != nil {
		limitVal = int(*limit)
	}

	offsetVal := 0
	if offset != nil {
		offsetVal = int(*offset)
	}

	users, err := r.UserRepo.List(limitVal, offsetVal)
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	result := make([]*model.User, len(users))
	for i := range users {
		result[i] = toGraphQLUser(&users[i])
	}

	return result, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id string) (*model.Chat, error) {
	chatID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	chat, err := r.ChatRepo.GetByID(chatID)
	if err != nil {
		return nil, fmt.Errorf("chat not found: %w", err)
	}

	return toGraphQLChat(chat), nil
}

// Chats is the resolver for the chats field.
func (r *queryResolver) Chats(ctx context.Context, limit *int32, offset *int32) ([]*model.Chat, error) {
	limitVal := 100
	if limit != nil {
		limitVal = int(*limit)
	}

	offsetVal := 0
	if offset != nil {
		offsetVal = int(*offset)
	}

	chats, err := r.ChatRepo.List(limitVal, offsetVal)
	if err != nil {
		return nil, fmt.Errorf("failed to list chats: %w", err)
	}

	result := make([]*model.Chat, len(chats))
	for i := range chats {
		result[i] = toGraphQLChat(&chats[i])
	}

	return result, nil
}

// ChatHistory is the resolver for the chatHistory field.
func (r *queryResolver) ChatHistory(ctx context.Context, id string) (*model.ChatHistory, error) {
	historyID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid chat history ID: %w", err)
	}

	history, err := r.ChatHistoryRepo.GetByID(historyID)
	if err != nil {
		return nil, fmt.Errorf("chat history not found: %w", err)
	}

	return toGraphQLChatHistory(history), nil
}

// ChatHistories is the resolver for the chatHistories field.
func (r *queryResolver) ChatHistories(ctx context.Context, chatID string, limit *int32) ([]*model.ChatHistory, error) {
	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, fmt.Errorf("invalid chat ID: %w", err)
	}

	limitVal := 100
	if limit != nil {
		limitVal = int(*limit)
	}

	histories, err := r.ChatHistoryRepo.GetByChatID(chatUUID, limitVal)
	if err != nil {
		return nil, fmt.Errorf("failed to list chat histories: %w", err)
	}

	result := make([]*model.ChatHistory, len(histories))
	for i := range histories {
		result[i] = toGraphQLChatHistory(&histories[i])
	}

	return result, nil
}

// Diary is the resolver for the diary field.
func (r *queryResolver) Diary(ctx context.Context, userID string) (*model.Diary, error) {
	userIDUint, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	diary, err := r.DiaryRepo.GetByUserID(uint(userIDUint))
	if err != nil {
		return nil, fmt.Errorf("diary not found: %w", err)
	}

	return toGraphQLDiary(diary), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func toGraphQLUser(user *models.User) *model.User {
	return &model.User{
		ID:        fmt.Sprintf("%d", user.ID),
		Name:      user.Name,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}
}

func toGraphQLChat(chat *models.Chat) *model.Chat {
	users := make([]*model.User, len(chat.Users))
	for i := range chat.Users {
		users[i] = toGraphQLUser(&chat.Users[i])
	}

	return &model.Chat{
		ID:        chat.ID.String(),
		Name:      chat.Name,
		Users:     users,
		CreatedAt: chat.CreatedAt,
		UpdatedAt: chat.UpdatedAt,
	}
}

func toGraphQLChatHistory(history *models.ChatHistory) *model.ChatHistory {
	historyType := history.Type
	if historyType == "" {
		historyType = "normal"
	}
	return &model.ChatHistory{
		ID:          history.ID.String(),
		ChatID:      history.ChatID.String(),
		UserID:      fmt.Sprintf("%d", history.UserID),
		MessageText: history.MessageText,
		Type:        historyType,
		CreatedAt:   time.Unix(history.CreatedAt, 0),
	}
}

func toGraphQLDiary(diary *models.Diary) *model.Diary {
	data := make(map[string]any)
	if diary.Data != nil {
		data = map[string]any(diary.Data)
	}
	return &model.Diary{
		ID:        fmt.Sprintf("%d", diary.ID),
		UserID:    fmt.Sprintf("%d", diary.UserID),
		ChatID:    diary.ChatID.String(),
		Data:      data,
		CreatedAt: diary.CreatedAt,
		UpdatedAt: diary.UpdatedAt,
	}
}
